language: objective-c
script: xcodebuild -workspace TravisExample.xcworkspace -scheme TravisExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcode_project: YJ.xcodeproj # 项目文件相对于.travis.yml文件的路径
xcode_scheme: YJ project #你需要集成测试的scheme